### ISSUE TITLE
Switch to calling Perl 6 "Raku" in the README

### ISSUE THREAD

**Issue by masak** [masak/alma#554]
And maybe in other places in the repository.

**Comment by QhpAptyj9hj0RQwMOw3ujuO3GDP3kYzkmXSh4gk** [comment]
Hey masak,

I'm happy to go through the README and the repo and change this.

**Comment by masak** [comment]
@QhpAptyj9hj0RQwMOw3ujuO3GDP3kYzkmXSh4gk That's very genteel of you. Please do it as a PR, and I'll make sure to merge it.

**Comment by QhpAptyj9hj0RQwMOw3ujuO3GDP3kYzkmXSh4gk** [comment]
You might remember me as John Smith ;)

I'm also working on updating the object names using https://docs.raku.org/language/intro

Unfortunately, grepping to change the object names in this document breaks the code for some reason. I'll play around with it to see if it was just a bad grep.

**Comment by masak** [comment]
Ok, please do that one as a separate PR, though. I'm eager to avoid scope creep (and I care a tad more about using the "Raku" name in outwards-facing documents than in code).

**Comment by masak** [comment]
Opting to close this one, as it has been fulfilled already.
