### ISSUE TITLE
Will no longer be updated to the Raku ecosystem

### ISSUE THREAD

**Issue by lizmat** [masak/alma#580]
Hello,

Thank you for the time and effort you have put in what is now the [Raku Programming Language](https://raku.org).  The language and its ecosystem are [moving forward](https://github.com/Raku/problem-solving/pull/318).

This means that these distributions:

- https://github.com/masak/007
- https://github.com/masak/Adventure-Engine
- https://github.com/masak/crypt
- https://github.com/masak/data-pretty
- https://github.com/masak/druid
- https://github.com/masak/gge
- https://github.com/masak/perl6-literate
- https://github.com/masak/text-indented
- https://github.com/masak/ufo
- https://github.com/masak/xml-writer
- https://github.com/masak/yapsi

will no longer be checked for updates by the Raku ecosystem.

This means that you will need to move your module to the [zef ecosystem](https://deathbykeystroke.com/articles/20210120-faq-zef-ecosystem.html) on the next update you make to these distributions.  Otherwise your update will simply not be seen by the ecosystem.

If you are no longer interested in maintaining these distributions, you can have these distributions moved to [Raku Community Modules Adoption Center](https://github.com/raku-community-modules/), where members of the Raku Community will take care of them.

This can be as easy as confirming that in a response to this issue.

Again, thank you for your time and efforts!

On behalf of the Raku Steering Council,

Elizabeth Mattijsen

**Comment by masak** [comment]
Hi, @lizmat!

Sorry for the late reply. I simply didn't notice this issue until now.

> Thank you for the time and effort you have put in what is now the [Raku Programming Language](https://raku.org/). The language and its ecosystem are [moving foward](https://github.com/Raku/problem-solving/pull/318).

Thank you! As I'm not tracking things all that closely these days, that is nice to hear.

> This means that these distributions: [...] will no longer be checked for updates by the Raku ecosystem.

Well! Seeing the URLs for those repositories put me in 11 kinds of nostalgia. I did not expect that.

To be quite honest, there have been no updates to those modules, and it is unlikely there will be any. (Except for the 007 repo, which is now the Alma repo.) These repositories, with perhaps one or two exceptions, fall on a spectrum between "barely implemented idea" and "module with a user base of one".

> If you are no longer interested in maintaining these distributions, you can have these distributions moved to [Raku Community Modules Adoption Center](https://github.com/raku-community-modules/), where members of the Raku Community will take care of them.

Hm, I'm not sure that's necessary. I expect the code in these modules not to be in high demand.

> Again, thank you for your time and efforts!

You're welcome! And thank you for reminding me of code I wrote a dozen or so years ago! :smile:

(closing)
